### ISSUE TITLE
Zoom URL is not valid

### ISSUE THREAD

**Issue by MJ94** [hyunbinseo/zoom-rec-dl#1]
Hi,

Does this tool work with Zoom vanity URLs (for example, if my recording link is https://mycompany.zoom.us/rec/share/longsharecode)? I receive "Error: Zoom URL is not valid" even after confirming the share URL and proper download settings.

**Comment by hyunbinseo** [comment]
As of now, if the Zoom URL does not match the following regular expression, it throws a `Zoom URL is not valid` error.

https://github.com/hyunbinseo/zoom-rec-dl/blob/039694320c1261ef008ef3b99f6ab2d92a93a271/index.mjs#L15

If you can provide a safe-to-share URL that works, I can update the code to support it.

**Comment by MJ94** [comment]
Do you have anywhere I can send a link privately so we can look into this?

**Comment by hyunbinseo** [comment]
If you have a Twitter account, DM me [@hyunbinseo97](https://twitter.com/hyunbinseo97)

**Comment by MJ94** [comment]
It looks like your DMs are closed. Can you please open them or DM @MJack94?

**Comment by MJ94** [comment]
Thank you for your responsiveness and the workaround until you can implement the code fix!

**Comment by hyunbinseo** [comment]
Fixed in https://github.com/hyunbinseo/zoom-rec-dl/commit/843cdd895ec86247bbf44fc77f5ad28b5edd78b0. Please re-download the script.
