### ISSUE TITLE
Downloading same file multiple times

### ISSUE THREAD

**Issue by surya-ravi** [hyunbinseo/zoom-rec-dl#12]
Hello! I was just wondering is this behaviour normal. The same file seems to get downloaded twice. Please check.

<img width="889" alt="Screenshot 2023-03-27 at 8 18 00 PM" src="https://user-images.githubusercontent.com/82202595/227976523-f32c8041-db4c-4105-af69-b7ddd3e51f8d.png">

**Comment by hyunbinseo** [comment]
That is abnormal. I can add a duplicate check. Could you provide the Zoom cloud recording URL that is causing the issue?

**Comment by surya-ravi** [comment]
Hello its a bit confidential sorry. Would the recording link without password be helpful?

Thank you so much for your work, it was a life saver for us to archive our cloud recordings

**Comment by hyunbinseo** [comment]
I am afraid that you have to provide a reproducible example, including the password.

You can create a blank Zoom cloud recording and send it to me via email.

**Comment by hyunbinseo** [comment]
A possible fix is being released in a few days.

**Comment by hyunbinseo** [comment]
Fixed in `2.0.1` https://github.com/hyunbinseo/zoom-rec-dl/commit/fef5f4563d61d8dba8b2b07dfaf471163ba483f5
