### ISSUE TITLE
File ID not found error

### ISSUE THREAD

**Issue by surya-ravi** [hyunbinseo/zoom-rec-dl#16]
<img width="642" alt="Screenshot 2023-04-26 at 11 15 31 AM" src="https://user-images.githubusercontent.com/82202595/234480647-06c291f8-7644-432e-956d-e1af2bef9911.png">

Can you help figure out why this is happening?

**Comment by hyunbinseo** [comment]
Could you provide a reproducible URL? I need more information.

**Comment by surya-ravi** [comment]
https://us02web.zoom.us/rec/share/ZQTx5bTtgE3hLPclNSoBGjcAItyL7HLByS2eAMV77bxM9bO7Les9GcLx653MhA8.gK2J0O6s0gvoIIiC?pwd=o6LrdpjnhnmjKdHaSC5UTC380UTfdo2v

**Comment by hyunbinseo** [comment]
The provided link requires a form submission. Can you check the link in incognito mode?

![image](https://user-images.githubusercontent.com/47051820/234494507-9c932b95-c4b1-48d1-bd7e-1dad059d1c58.png)

**Comment by hyunbinseo** [comment]
The following message will be shown in 2.1.2+. b63c9ccdfa7ce24bd7f0d5cbd8d9a0ca61bc36ce

```
2023-04-26T07:03:35.213Z ┌ ZQTx5bTtgE3hLPclNSoB
2023-04-26T07:03:36.196Z └ Valid token is not found. Check if the URL requires additional actions.
```

**Comment by surya-ravi** [comment]
<img width="1053" alt="Screenshot 2023-04-26 at 12 37 52 PM" src="https://user-images.githubusercontent.com/82202595/234496870-41060115-29aa-4c2c-b0bd-b8806b75bca1.png">
 
I believe its related to this option. Its working now after I disabled it.

**Comment by hyunbinseo** [comment]
Thank you for the information. On-demand related documentation will be applied in the next release. 647e284f26997cfd521d5dd2b01af83ed3f25efb
