### ISSUE TITLE
Hi I liked, thank you!

### ISSUE THREAD

**Issue by moyamiga** [hyunbinseo/zoom-rec-dl#2]
I I have an error with the links that start with

"https://us02web.zoom.us/rec/share/K5...

I delete the subdomine and its working

"https://zoom.us/rec/share/K5....

Thank you

**Comment by hyunbinseo** [comment]
Fixed in https://github.com/hyunbinseo/zoom-rec-dl/commit/f9517df2f65601fd4b078200172c6814c00abad6. Can you re-download the script and check if it works?
