### ISSUE TITLE
The file doesn't seem to open

### ISSUE THREAD

**Issue by hsgautam** [hyunbinseo/zoom-rec-dl#26]
**Describe the bug**
file:///Users/gautambhatt/.npm/_npx/0acb851b9f9f67be/node_modules/zoom-rec-dl/dist/index.js:24
    throw new Error(`No valid URL(s) are found. Please check the ${urlTextFilename} file.`);
          ^

Error: No valid URL(s) are found. Please check the urls.txt file.
    at file:///Users/gautambhatt/.npm/_npx/0acb851b9f9f67be/node_modules/zoom-rec-dl/dist/index.js:24:11
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.14.0

**Cloud recording URL**
Any Zoom link that reproduces the issue.

**Additional context**
The file has the URLs

**Comment by hyunbinseo** [comment]
The `urls.txt` file does exist and is recognized by the CLI.

Can you share some of the urls inside the text file? You can replace sensitive parts.

https://github.com/hyunbinseo/zoom-rec-dl/blob/443b7dcdc8f1ea49d762ea23a4b2b6cd2eb045b2/src/index.ts#L50

The URLs inside `urls.txt` file do not seem to satisfy the above regular expression.
