### ISSUE TITLE
The Zoom URL is not valid.

### ISSUE THREAD

**Issue by KCarterSr** [hyunbinseo/zoom-rec-dl#6]
Thanks for the great script.

The problem I'm having is that when I'm on the zoom site, on the page that shows all the recording and I click the "share button to get the URL, your program "DOES WORK" with that URL. 

However, if when on the zoom site and I click on a specific recording, all the files are listed for the meeting.
The recording includes the files listed below:

Shared screen with speaker view
Audio only
Chat File
Closed Caption

When I hover over "Audio only" for example, I can get the sharable URL for that file, but that URL throws an error in your program.  In fact, all the shareable URL's for Shared screen with speaker view, Audio only, Chat File, and Closed Caption, DO NOT WORK.

I think the problem is with the RegEx.

Can you take a look at this problem?

Thank you
K. L. Carter Sr.

**Comment by hyunbinseo** [comment]
Can you share an example 'audio only' link? The current script only supports `.mp4` files.

**Comment by KCarterSr** [comment]
.mp4    , GMT20230105-223835_Recording_640x360.mp4 , NOT WORKING EXAMPLE : https://us06web.zoom.us/rec/play/EtePJxHMygI-DvguT3DdVQIlLMwKLdez1cnjXVr9vNW8B_dehqIvz3Iv9Fa8MAKMRr1ldMdcFDbwvmpK.VbpWIKSkjlB9GVql

.m4a    , GMT20230105-223835_Recording.m4a , Audio only NOT WORKING EXAMPLE : https://us06web.zoom.us/rec/play/NBr_dJBx_0yypH6huzdVE_ZZeM5ZjWSNX6lzsIkZ7JGdzx0B1Gm72LOixTCPOkOoJwgMo9zgYYu1Ih4w.arwm-3yLOVz_TMAf
 
.txt    , GMT20230105-223835_Recording.txt , Chat File NOT WORKING EXAMPLE : https://us06web.zoom.us/rec/sdownload/dsK92zovB9WO-hUFd1Lp7MDlWmIaQzFTliNt2YcdsN88eL_a6XnyUTpk2YHcq9xdcT13gL7nblVI7MsI.kyZLBRisqHwDf3_Z

.cc.vtt , GMT20230105-223835_Recording.cc.vtt , Closed Caption NOT WORKING EXAMPLE : https://us06web.zoom.us/rec/sdownload/Vh96xPV-_Fytda0h8OF_Gvl40yPFBncodds0L4FHm7sfYms5vZqJOLdannD9joze18kMG8VpPXVz3ljU.qZZUZZ5ArL4a2WiD

**Comment by hyunbinseo** [comment]
Fixed in https://github.com/hyunbinseo/zoom-rec-dl/commit/27158b8193bebee7884a665dfff92e8e3493780c.

- `/rec/play` path is now supported.
- `.m4a` audio files are now supported.

---

`.txt` and `.cc.vtt` file URLs do not require a download script.

Simply use browser extensions such as [Open Multiple URLs](https://github.com/htrinter/Open-Multiple-URLs).

**Comment by KCarterSr** [comment]
Thank you very much.

**Comment by KCarterSr** [comment]
Hi, 
I just got around to testing this. I'm getting Zoom URL is not Valid on these.

(node:4944) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///J:/Lina%20Zoom%20Videos/HYUNBINSEO%20HYUNBIN%20-%20ZOOM-REC-DL/index.mjs:68
        if (!regex.zoomShare.test(url)) throw new Error(`Zoom URL is not valid. (${url})`);
                                              ^

Error: Zoom URL is not valid. (https://us06web.zoom.us/rec/play/Ae29JK0apdHkd5v46IyTJOpCzzRdr_BuOz3M9sFjzMU7FNUFpIwISeYe0Y0hzR3YqtoTJ8FLnWMV6iU.ldAF6OsR3p8vST4n)
    at file:///J:/Lina%20Zoom%20Videos/HYUNBINSEO%20HYUNBIN%20-%20ZOOM-REC-DL/index.mjs:68:40
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.13.0

"https://us06web.zoom.us/rec/play/Ae29JK0apdHkd5v46IyTJOpCzzRdr_BuOz3M9sFjzMU7FNUFpIwISeYe0Y0hzR3YqtoTJ8FLnWMV6iU.ldAF6OsR3p8vST4n",
        "https://us06web.zoom.us/rec/play/7TJ1tQLEp4WIbY0XijhEDhf0-S5hnD3307hAGh5Ogm2dDmk7WhRDATQRa8gbrzWbcQo3BiT8ww3_X_pT.nsPwwDIkFGz1hUG6"
