### ISSUE TITLE
(New released version) Zoom URL is not Valid

### ISSUE THREAD

**Issue by KCarterSr** [hyunbinseo/zoom-rec-dl#7]
Hi,
I just got around to testing the new release. I'm getting Zoom URL is not Valid on these.

(node:4944) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use node --trace-warnings ... to show where the warning was created)
file:///J:/Lina%20Zoom%20Videos/HYUNBINSEO%20HYUNBIN%20-%20ZOOM-REC-DL/index.mjs:68
if (!regex.zoomShare.test(url)) throw new Error(Zoom URL is not valid. (${url}));
^

Error: Zoom URL is not valid. (https://us06web.zoom.us/rec/play/Ae29JK0apdHkd5v46IyTJOpCzzRdr_BuOz3M9sFjzMU7FNUFpIwISeYe0Y0hzR3YqtoTJ8FLnWMV6iU.ldAF6OsR3p8vST4n)
at file:///J:/Lina%20Zoom%20Videos/HYUNBINSEO%20HYUNBIN%20-%20ZOOM-REC-DL/index.mjs:68:40
at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.13.0

"https://us06web.zoom.us/rec/play/Ae29JK0apdHkd5v46IyTJOpCzzRdr_BuOz3M9sFjzMU7FNUFpIwISeYe0Y0hzR3YqtoTJ8FLnWMV6iU.ldAF6OsR3p8vST4n"

"https://us06web.zoom.us/rec/play/7TJ1tQLEp4WIbY0XijhEDhf0-S5hnD3307hAGh5Ogm2dDmk7WhRDATQRa8gbrzWbcQo3BiT8ww3_X_pT.nsPwwDIkFGz1hUG6"

Thank you

**Comment by hyunbinseo** [comment]
You are not using the latest script. Could you re-download and re-try?

The following JSON file works fine for me.

```json
[
	"https://us06web.zoom.us/rec/play/Ae29JK0apdHkd5v46IyTJOpCzzRdr_BuOz3M9sFjzMU7FNUFpIwISeYe0Y0hzR3YqtoTJ8FLnWMV6iU.ldAF6OsR3p8vST4n",
	"https://us06web.zoom.us/rec/play/7TJ1tQLEp4WIbY0XijhEDhf0-S5hnD3307hAGh5Ogm2dDmk7WhRDATQRa8gbrzWbcQo3BiT8ww3_X_pT.nsPwwDIkFGz1hUG6"
]

```

**Comment by hyunbinseo** [comment]
Is it working now? The latest version uses `index.js` file, not `index.mjs`.

**Comment by KCarterSr** [comment]
Yes, It's working now.
Thank you
