### ISSUE TITLE
URL with password not working.

### ISSUE THREAD

**Issue by KCarterSr** [hyunbinseo/zoom-rec-dl#8]
When I use a URL with the password it fails.

https://us06web.zoom.us/rec/play/jX5hTS_42dpTloEGWseCIiXbYQzRIqqumRMYg_63FcA6-U34IRPR47WR4rRJ7bqVYOJc4NneFm6P9nsq.l9dvJogP5Q2NaKBF

I'm using ?pwd=xxxxxxxx  at the end of the URL

By the way it could be that the password also starts with a equal sign. So, in my case it would be 
?pwd==xxxxxxxx

I can email you the password if I have your email address.

Thanks again.

**Comment by hyunbinseo** [comment]
Could you provide a minimum reproducible example - an example that can be shared publicly on GitHub issue?

**Comment by hyunbinseo** [comment]
There are two types of recording passwords - manual entry and URL embedded.

Only the latter is supported. Please reference the [requirements](https://github.com/hyunbinseo/zoom-rec-dl#requirements) documentation.

> Should show a media player and a download button. Should not show an 'Enter the passcode to watch' message.

**Comment by KCarterSr** [comment]
Thanks
